const WORD_DATABASE = {
	easy: {
		lanes: 3,
		speed: 1.5,
		spawnInterval: 1800,
		positiveRatio: 0.8,
		words: [
			// Positive (core Spiritual Playdate values – simple)
			{text: "Respect", type: "positive"},
			{text: "Kindness", type: "positive"},
			{text: "Empathy", type: "positive"},
			{text: "Listening", type: "positive"},
			{text: "Sharing", type: "positive"},
			{text: "Helpful", type: "positive"},
			{text: "Fairness", type: "positive"},
			{text: "Inclusion", type: "positive"},
			{text: "Love", type: "positive"},
			{text: "Forgiveness", type: "positive"},
			{text: "Gratitude", type: "positive"},
			{text: "Peace", type: "positive"},
			{text: "Caring", type: "positive"},
			{text: "Gentle", type: "positive"},
			{text: "Honest", type: "positive"},
			{text: "Brave", type: "positive"},
			{text: "Friendly", type: "positive"},
			{text: "Thankful", type: "positive"},
			{text: "Polite", type: "positive"},
			{text: "Support", type: "positive"},
			{text: "Joy", type: "positive"},
			{text: "Hope", type: "positive"},
			{text: "Trust", type: "positive"},
			{text: "Calm", type: "positive"},
			{text: "Smile", type: "positive"},
			{text: "Hug", type: "positive"},
			{text: "Share", type: "positive"},
			{text: "Help", type: "positive"},
			{text: "Listen", type: "positive"},
			{text: "Care", type: "positive"},
			{text: "Safe", type: "positive"},
			{text: "Kind", type: "positive"},
			{text: "Nice", type: "positive"},
			{text: "Happy", type: "positive"},
			{text: "Friend", type: "positive"},
			{text: "Together", type: "positive"},
			{text: "Welcome", type: "positive"},
			{text: "Accept", type: "positive"},
			{text: "Include", type: "positive"},
			{text: "Equal", type: "positive"},
			{text: "Fair", type: "positive"},
			{text: "Gentle", type: "positive"},
			{text: "Soft", type: "positive"},
			{text: "Quiet", type: "positive"},
			{text: "Peaceful", type: "positive"},
			{text: "Loving", type: "positive"},
			{text: "Grateful", type: "positive"},
			{text: "Sorry", type: "positive"},
			{text: "Forgive", type: "positive"},
			{text: "Thank", type: "positive"},
			{text: "Appreciate", type: "positive"},
			{text: "Respectful", type: "positive"},
			{text: "Patient", type: "positive"},
			{text: "Understanding", type: "positive"},
			{text: "Compassionate", type: "positive"},
			{text: "Supportive", type: "positive"},
			{text: "Encouraging", type: "positive"},
			{text: "Uplifting", type: "positive"},
			{text: "Positive", type: "positive"},
			{text: "Hopeful", type: "positive"},
			{text: "Courage", type: "positive"},
			{text: "Strength", type: "positive"},
			{text: "Balance", type: "positive"},
			{text: "Harmony", type: "positive"},
			{text: "Unity", type: "positive"},
			{text: "Connection", type: "positive"},
			{text: "Belonging", type: "positive"},
			{text: "Dignity", type: "positive"},
			{text: "Worth", type: "positive"},
			{text: "Value", type: "positive"},
			{text: "Mindful", type: "positive"},
			{text: "Aware", type: "positive"},
			{text: "Present", type: "positive"},
			{text: "Open", type: "positive"},
			{text: "Curious", type: "positive"},
			{text: "Wonder", type: "positive"},
			{text: "Sacred", type: "positive"},
			{text: "Holy", type: "positive"},
			{text: "Spirit", type: "positive"},
			{text: "Soul", type: "positive"},
			{text: "Heart", type: "positive"},
			{text: "Golden", type: "positive"}, // Golden Rule
			{text: "Rule", type: "positive"},
			{text: "Treat", type: "positive"},
			{text: "Yourself", type: "positive"},
			{text: "Neighbor", type: "positive"},
			{text: "Community", type: "positive"},
			{text: "Family", type: "positive"},
			{text: "Playdate", type: "positive"},
			{text: "Dialogue", type: "positive"},
			{text: "Talk", type: "positive"},
			{text: "Share", type: "positive"},
			{text: "Learn", type: "positive"},
			{text: "Grow", type: "positive"},
			{text: "Explore", type: "positive"},
			{text: "Discover", type: "positive"},
			{text: "Bridge", type: "positive"},
			{text: "Build", type: "positive"},
			{text: "Peaceful", type: "positive"},

			// Negative (simple opposites)
			{text: "Rude", type: "negative"},
			{text: "Mean", type: "negative"},
			{text: "Hate", type: "negative"},
			{text: "Bully", type: "negative"},
			{text: "Hurt", type: "negative"},
			{text: "Fight", type: "negative"},
			{text: "Yell", type: "negative"},
			{text: "Ignore", type: "negative"},
			{text: "Exclude", type: "negative"},
			{text: "Selfish", type: "negative"},
			{text: "Greedy", type: "negative"},
			{text: "Angry", type: "negative"},
			{text: "Jealous", type: "negative"},
			{text: "Lie", type: "negative"},
			{text: "Cheat", type: "negative"},
			{text: "Steal", type: "negative"},
			{text: "Push", type: "negative"},
			{text: "Tease", type: "negative"},
			{text: "Insult", type: "negative"},
			{text: "Mock", type: "negative"},
		],
	},

	medium: {
		lanes: 4,
		speed: 2.2,
		spawnInterval: 1400,
		positiveRatio: 0.7,
		words: [
			// Positive
			{text: "Respect", type: "positive"},
			{text: "Compassion", type: "positive"},
			{text: "Patience", type: "positive"},
			{text: "Gratitude", type: "positive"},
			{text: "Teamwork", type: "positive"},
			{text: "Integrity", type: "positive"},
			{text: "Empathy", type: "positive"},
			{text: "Kindness", type: "positive"},
			{text: "Forgiveness", type: "positive"},
			{text: "Love", type: "positive"},
			{text: "Peace", type: "positive"},
			{text: "Inclusion", type: "positive"},
			{text: "Fairness", type: "positive"},
			{text: "Dignity", type: "positive"},
			{text: "Courage", type: "positive"},
			{text: "Resilience", type: "positive"},
			{text: "Understanding", type: "positive"},
			{text: "Acceptance", type: "positive"},
			{text: "Listening", type: "positive"},
			{text: "Sharing", type: "positive"},
			{text: "Helpfulness", type: "positive"},
			{text: "Honesty", type: "positive"},
			{text: "Trust", type: "positive"},
			{text: "Hope", type: "positive"},
			{text: "Joy", type: "positive"},
			{text: "Harmony", type: "positive"},
			{text: "Unity", type: "positive"},
			{text: "Connection", type: "positive"},
			{text: "Belonging", type: "positive"},
			{text: "Mindfulness", type: "positive"},
			{text: "Awareness", type: "positive"},
			{text: "Self-control", type: "positive"},
			{text: "Self-awareness", type: "positive"},
			{text: "Interpersonal", type: "positive"},
			{text: "Critical thinking", type: "positive"},
			{text: "Golden Rule", type: "positive"},
			{text: "In Lak'ech", type: "positive"},
			{text: "Nonviolence", type: "positive"},
			{text: "Peacemaking", type: "positive"},
			{text: "Justice", type: "positive"},
			{text: "Equity", type: "positive"},
			{text: "Solidarity", type: "positive"},
			{text: "Interfaith", type: "positive"},
			{text: "Dialogue", type: "positive"},
			{text: "Curiosity", type: "positive"},
			{text: "Wonder", type: "positive"},
			{text: "Sacred", type: "positive"},
			{text: "Spiritual", type: "positive"},
			{text: "Soul Talk", type: "positive"},
			{text: "Playdate", type: "positive"},
			{text: "Affirmation", type: "positive"},
			{text: "Encouragement", type: "positive"},
			{text: "Support", type: "positive"},
			{text: "Uplift", type: "positive"},
			{text: "Heal", type: "positive"},
			{text: "Restore", type: "positive"},
			{text: "Reconcile", type: "positive"},
			{text: "Bridge", type: "positive"},
			{text: "Build", type: "positive"},
			{text: "Grow", type: "positive"},
			{text: "Learn", type: "positive"},
			{text: "Explore", type: "positive"},
			{text: "Discover", type: "positive"},
			{text: "Reflect", type: "positive"},
			{text: "Meditate", type: "positive"},
			{text: "Breathe", type: "positive"},
			{text: "Calm", type: "positive"},
			{text: "Center", type: "positive"},
			{text: "Balance", type: "positive"},
			{text: "Body", type: "positive"},
			{text: "Mind", type: "positive"},
			{text: "Soul", type: "positive"},
			{text: "Heart", type: "positive"},
			{text: "Spirit", type: "positive"},
			{text: "Faith", type: "positive"},
			{text: "Belief", type: "positive"},
			{text: "Tradition", type: "positive"},
			{text: "World religions", type: "positive"},
			{text: "Sacred spaces", type: "positive"},
			{text: "Holy books", type: "positive"},
			{text: "Teachers", type: "positive"},
			{text: "Wisdom", type: "positive"},
			{text: "Guidance", type: "positive"},
			{text: "Purpose", type: "positive"},
			{text: "Meaning", type: "positive"},
			{text: "Values", type: "positive"},
			{text: "Principles", type: "positive"},
			{text: "Character", type: "positive"},
			{text: "Virtue", type: "positive"},
			{text: "Altruism", type: "positive"},
			{text: "Generosity", type: "positive"},
			{text: "Service", type: "positive"},
			{text: "Community", type: "positive"},
			{text: "Family", type: "positive"},
			{text: "Friendship", type: "positive"},
			{text: "Relationship", type: "positive"},
			{text: "Communication", type: "positive"},
			{text: "Expression", type: "positive"},
			{text: "Feelings", type: "positive"},
			{text: "Emotions", type: "positive"},

			// Negative
			{text: "Bullying", type: "negative"},
			{text: "Insult", type: "negative"},
			{text: "Selfish", type: "negative"},
			{text: "Arrogant", type: "negative"},
			{text: "Exclusion", type: "negative"},
			{text: "Hostility", type: "negative"},
			{text: "Jealousy", type: "negative"},
			{text: "Hatred", type: "negative"},
			{text: "Violence", type: "negative"},
			{text: "Prejudice", type: "negative"},
			{text: "Discrimination", type: "negative"},
			{text: "Intolerance", type: "negative"},
			{text: "Greed", type: "negative"},
			{text: "Envy", type: "negative"},
			{text: "Anger", type: "negative"},
			{text: "Resentment", type: "negative"},
			{text: "Grudge", type: "negative"},
			{text: "Bitterness", type: "negative"},
			{text: "Cruelty", type: "negative"},
			{text: "Meanness", type: "negative"},
			{text: "Rudeness", type: "negative"},
			{text: "Disrespect", type: "negative"},
			{text: "Neglect", type: "negative"},
			{text: "Isolation", type: "negative"},
			{text: "Division", type: "negative"},
			{text: "Conflict", type: "negative"},
			{text: "Aggression", type: "negative"},
			{text: "Harm", type: "negative"},
			{text: "Hurt", type: "negative"},
			{text: "Pain", type: "negative"},
		],
	},

	hard: {
		lanes: 4,
		speed: 3.0,
		spawnInterval: 1000,
		positiveRatio: 0.6,
		words: [
			// Positive (more advanced / nuanced Spiritual Playdate language)
			{text: "Dignity", type: "positive"},
			{text: "Courage", type: "positive"},
			{text: "Altruism", type: "positive"},
			{text: "Collaboration", type: "positive"},
			{text: "Compassion", type: "positive"},
			{text: "Empathy", type: "positive"},
			{text: "Integrity", type: "positive"},
			{text: "Resilience", type: "positive"},
			{text: "Forgiveness", type: "positive"},
			{text: "Gratitude", type: "positive"},
			{text: "Respect", type: "positive"},
			{text: "Inclusion", type: "positive"},
			{text: "Equity", type: "positive"},
			{text: "Justice", type: "positive"},
			{text: "Nonviolence", type: "positive"},
			{text: "Peacemaking", type: "positive"},
			{text: "Reconciliation", type: "positive"},
			{text: "Interfaith", type: "positive"},
			{text: "Dialogue", type: "positive"},
			{text: "Understanding", type: "positive"},
			{text: "Acceptance", type: "positive"},
			{text: "Belonging", type: "positive"},
			{text: "Connectedness", type: "positive"},
			{text: "Mindfulness", type: "positive"},
			{text: "Self awareness", type: "positive"},
			{text: "Self regulation", type: "positive"},
			{text: "Emotional intelligence", type: "positive"},
			{text: "Critical thinking", type: "positive"},
			{text: "Golden Rule", type: "positive"},
			{text: "In Lak'ech", type: "positive"},
			{text: "Reciprocity", type: "positive"},
			{text: "Sacred spaces", type: "positive"},
			{text: "Spiritual teachers", type: "positive"},
			{text: "Holy texts", type: "positive"},
			{text: "World religions", type: "positive"},
			{text: "Religious literacy", type: "positive"},
			{text: "Universal truths", type: "positive"},
			{text: "Guiding principles", type: "positive"},
			{text: "Life skills", type: "positive"},
			{text: "Soul Talks", type: "positive"},
			{text: "Pop-up Playdate", type: "positive"},
			{text: "Peace education", type: "positive"},
			{text: "Holistic", type: "positive"},
			{text: "Body mind soul", type: "positive"},
			{text: "Inner practice", type: "positive"},
			{text: "Daily care", type: "positive"},
			{text: "Purpose", type: "positive"},
			{text: "Meaning", type: "positive"},
			{text: "Wisdom", type: "positive"},
			{text: "Discernment", type: "positive"},
			{text: "Humility", type: "positive"},
			{text: "Vulnerability", type: "positive"},
			{text: "Authenticity", type: "positive"},
			{text: "Agency", type: "positive"},
			{text: "Empowerment", type: "positive"},
			{text: "Solidarity", type: "positive"},
			{text: "Allyship", type: "positive"},
			{text: "Advocacy", type: "positive"},
			{text: "Spiritual protest", type: "positive"},
			{text: "Conscious leadership", type: "positive"},
			{text: "Global community", type: "positive"},
			{text: "Bridge building", type: "positive"},
			{text: "Cultural humility", type: "positive"},
			{text: "Pluralism", type: "positive"},
			{text: "Diversity", type: "positive"},
			{text: "Equity", type: "positive"},
			{text: "Belonging", type: "positive"},
			{text: "Affirmation", type: "positive"},
			{text: "Validation", type: "positive"},
			{text: "Healing", type: "positive"},
			{text: "Restoration", type: "positive"},
			{text: "Transformation", type: "positive"},
			{text: "Growth mindset", type: "positive"},
			{text: "Emotional literacy", type: "positive"},
			{text: "Conflict resolution", type: "positive"},
			{text: "De-escalation", type: "positive"},
			{text: "Active listening", type: "positive"},
			{text: "Perspective taking", type: "positive"},
			{text: "Shared humanity", type: "positive"},
			{text: "Common ground", type: "positive"},
			{text: "Mutual respect", type: "positive"},
			{text: "Radical acceptance", type: "positive"},
			{text: "Unconditional regard", type: "positive"},
			{text: "Loving kindness", type: "positive"},
			{text: "Metta", type: "positive"},
			{text: "Ubuntu", type: "positive"},
			{text: "Ahimsa", type: "positive"},
			{text: "Satya", type: "positive"},
			{text: "Karuna", type: "positive"},
			{text: "Tikkun olam", type: "positive"},
			{text: "Stewardship", type: "positive"},
			{text: "Service", type: "positive"},
			{text: "Generosity of spirit", type: "positive"},
			{text: "Open heartedness", type: "positive"},
			{text: "Reverence", type: "positive"},
			{text: "Awe", type: "positive"},
			{text: "Wonder", type: "positive"},
			{text: "Mystery", type: "positive"},
			{text: "Transcendence", type: "positive"},
			{text: "Inter connectedness", type: "positive"},

			// Negative (more complex / nuanced opposites)
			{text: "Bullying", type: "negative"},
			{text: "Arrogance", type: "negative"},
			{text: "Exclusion", type: "negative"},
			{text: "Hostility", type: "negative"},
			{text: "Jealousy", type: "negative"},
			{text: "Prejudice", type: "negative"},
			{text: "Discrimination", type: "negative"},
			{text: "Intolerance", type: "negative"},
			{text: "Xenophobia", type: "negative"},
			{text: "Bigotry", type: "negative"},
			{text: "Hate speech", type: "negative"},
			{text: "Violence", type: "negative"},
			{text: "Aggression", type: "negative"},
			{text: "Retaliation", type: "negative"},
			{text: "Revenge", type: "negative"},
			{text: "Grudge-holding", type: "negative"},
			{text: "Resentment", type: "negative"},
			{text: "Bitterness", type: "negative"},
			{text: "Cynicism", type: "negative"},
			{text: "Apathy", type: "negative"},
			{text: "Indifference", type: "negative"},
			{text: "Alienation", type: "negative"},
			{text: "Isolation", type: "negative"},
			{text: "Division", type: "negative"},
			{text: "Polarization", type: "negative"},
			{text: "Othering", type: "negative"},
			{text: "Dehumanization", type: "negative"},
			{text: "Exploitation", type: "negative"},
			{text: "Oppression", type: "negative"},
			{text: "Injustice", type: "negative"},
			{text: "Inequity", type: "negative"},
			{text: "Selfishness", type: "negative"},
			{text: "Greed", type: "negative"},
			{text: "Entitlement", type: "negative"},
			{text: "Narcissism", type: "negative"},
			{text: "Contempt", type: "negative"},
			{text: "Disdain", type: "negative"},
			{text: "Mockery", type: "negative"},
			{text: "Ridicule", type: "negative"},
			{text: "Shaming", type: "negative"},
		],
	},
};